# Generated by Django 4.2.5 on 2024-09-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_emailschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.emailreminder'),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
